---
# tasks file for rsyslog
- name: include assert.yml
  include_tasks: assert.yml

- name: uninstall conflicting systemd-logger
  package:
    name: systemd-logger
    state: absent

- name: install rsyslog
  package:
    name: "{{ rsyslog_packages }}"
    state: present

- name: configuring rsyslog
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - restart rsyslog

- name: make configuration directory
  file:
    name: /etc/rsyslog.d/
    state: directory

- name: start and enable rsyslog
  service:
    name: "{{ rsyslog_service }}"
    state: started
    enabled: yes
