---
# tasks file for rsyslog
- name: uninstall conflicting software
  package:
    name: systemd-logger
    state: absent

- name: install software
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ rsyslog_packages }}"

- name: configuring software
  template:
    src: rsyslog.conf.j2
    dest: /etc/rsyslog.conf
  notify:
    - restart rsyslog

- name: make configuration directory
  file:
    name: /etc/rsyslog.d/
    state: directory

- name: start and enable software
  service:
    name: "{{ rsyslog_service }}"
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker"
